### ISSUE TITLE
When selected, how to make icon and title position rise

### ISSUE THREAD

**Issue by hanxu-zhao** [tommybuonomo/morph-bottom-navigation#17]
When selected, how to make icon and title position rise，I can change the size of icon and title, but I can’t change their position and make them rise. Can you help me, thanks

**Comment by TheKema** [comment]
Did you find a solution or analogue to this library?

**Comment by hanxu-zhao** [comment]
> Did you find a solution or analogue to this library?
yes, in MorphBottomNavigationViewTopEdgeTreatment file, you can move view by view.scrollTo (), when traversing the item, the selected item at this time makes it go up, the last selected item makes it go down
code:
 if (i == selectedItem) {
                    view.scrollTo(0, 36)
                } else if (i == lastSelectedItem) {
                    view.scrollTo(0, 0)
                }
