### ISSUE TITLE
Manifest merger failed : Attribute application@appComponentFactory

### ISSUE THREAD

**Issue by IdeoG** [tommybuonomo/morph-bottom-navigation#2]
Hello @tommybuonomo,
I have tried to create gradle tree with your library, but exception occured. 

OS: Manjaro 17.1.1
Android Studio: 3.2.20 Canary Branch

### Steps to reproduce
1. Create demo project with Android 28+ 
2. Build with default gradle.build
3. Added your library implementation
4. Exception occur

Here is exception backtrack: 

``` bash
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0-alpha3] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0-alpha3] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.


```

**Comment by atsen-dev** [comment]
I have the same problem on my project, do you have solved it ?

**Comment by IdeoG** [comment]
I didn't solve the issue. You can read another one issue, it was said the author use android sdk-28.0.0-alpha, but then sdk-27.1.1 was released about month ago, dependencies was broken.
I have no idea how to fix this.

**Comment by atsen-dev** [comment]
ok thanks, I will search to fix it

**Comment by IdeoG** [comment]
@assimtsenoussi Have you solved the issue?

**Comment by tommybuonomo** [comment]
@IdeoG I'm working on it :)

**Comment by tommybuonomo** [comment]
@IdeoG @assimtsenoussi 
I think you're not using the [android x](https://developer.android.com/topic/libraries/support-library/androidx-rn) format and this is why the build fail.
Can you [refactor](https://developer.android.com/topic/libraries/support-library/refactor) your projects ?
You can do it [via AndroidStudio](https://developer.android.com/studio/preview/features/#androidx_migration) but do it it carefully (commit your current work before) 
Best regards.

**Comment by atsen-dev** [comment]
thank you, after having done the refactoring it work for me.
So I did an update of Gradle and refactoring my project to solve it.
Android Studio 3.2 or later and gradle 3.2 or later needed to make refactoring to android x

@IdeoG @tommybuonomo

**Comment by AmanGoyal-Oodles** [comment]
add these two properties in gradle.properties file

android.useAndroidX=true
android.enableJetifier=true

It solved my problem.
