### ISSUE TITLE
How to use this library in api 25 (Java Code)

### ISSUE THREAD

**Issue by AliAminiP** [tommybuonomo/morph-bottom-navigation#8]
hey everyone
I just want to use this library in my Android(Java not Kotlin) project
my SDK properties are:
       compileSdkVersion 25
        minSdkVersion 21
        targetSdkVersion 23
and when I want to add this library to my project this error is shown :

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0-alpha3] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.0-alpha3] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:18:5-36:19 to override.

please help how can I solve this error or is there any way to use this library in API 25?
thank you
Regards.

**Comment by CodingPeaches90** [comment]
Hi AliAminiP,

Not sure if you got this issue fixed but the solution is to migrate to AndroidX. I assume you are using both the old android support libraries and new AndroidX libraries and thus you will face the above merger issue.

To migrate -> Refactor -> Migrate to AndroidX.
